name: file_picker_poc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.7.0
  # file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  plugin_mrz:
    git:
      url: https://ThinkDigital0@dev.azure.com/ThinkDigital0/Utilidades/_git/poc_fluter_pack_mrz
      ref: v1.0.3
  plugin_nfc:
    git:
      url: https://ThinkDigital0@dev.azure.com/ThinkDigital0/Utilidades/_git/poc_flutter_pack_nfc
      ref: v1.0.2
  plugin_liveness:
    git:
      url: https://ThinkDigital0@dev.azure.com/ThinkDigital0/Utilidades/_git/poc_flutter_pack_liveness
      ref: v1.0.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/plugin_nfc_messages.json
    - assets/plugin_liveness_messages.json
    - assets/plugin_liveness_lottie_loading.json
